import axios from 'axios';
const BASE = process.env.REACT_APP_ADMIN_API_URL || 'http://localhost:3011/api/v1/admin';
const PUBLIC_BASE = BASE.replace('/admin', '/public');
export const ADMIN_SOCKET_URL = BASE.replace(/\/api\/v1\/admin\/?$/, '');
const api = axios.create({ baseURL: BASE });
api.interceptors.request.use(cfg => { const t = localStorage.getItem('adminToken'); if (t) cfg.headers.Authorization = 'Bearer ' + t; return cfg; });
api.interceptors.response.use(r => r, err => { if (err.response?.status === 401) { localStorage.removeItem('adminToken'); window.location.href = '/login'; } return Promise.reject(err); });
export const adminLogin = d => api.post('/login', d);
export const getDashboard = () => api.get('/dashboard');
export const getRealtimeSnapshot = () => api.get('/realtime/snapshot');
export const getUsers = (p, search = '') => api.get('/users?page=' + p + '&search=' + encodeURIComponent(search));
export const banUser = id => api.put('/users/' + id + '/ban');
export const unbanUser = id => api.put('/users/' + id + '/unban');
export const getProfiles = params => api.get('/profiles', { params });
export const createProfile = payload => api.post('/profiles', payload);
export const bulkCreateProfiles = profiles => api.post('/profiles/bulk', { profiles });
export const updateProfile = (id, payload) => api.put('/profiles/' + id, payload);
export const deleteProfile = id => api.delete('/profiles/' + id);
export const updateProfileStatus = (id, action, reason = '') => api.put('/profiles/' + id + '/status', { action, reason });
export const getVerifications = () => api.get('/verifications');
export const approveVerification = (id, note = '') => api.put('/verifications/' + id + '/approve', { note });
export const rejectVerification = (id, note = '') => api.put('/verifications/' + id + '/reject', { note });
export const getReports = () => api.get('/moderation/reports');
export const resolveReport = id => api.put('/reports/' + id + '/resolve');
export const getChatLogs = () => api.get('/moderation/chat-logs');
export const getPayments = () => api.get('/payments');
export const createRefund = payload => api.post('/payments/refunds', payload);
export const getAlerts = () => api.get('/alerts');
export const acknowledgeAlert = id => api.put('/alerts/' + id + '/ack');
export const createCampaign = payload => api.post('/campaigns', payload);
export const getAuditLogs = (limit = 100) => api.get('/audit-logs?limit=' + limit);
export const getRoles = () => api.get('/roles');
export const getConfig = () => api.get('/config');
export const updateConfig = (key, payload) => api.put('/config/' + key, payload);
export const getLandingPages = () => api.get('/landing-pages');
export const saveLandingPage = (slug, payload) => slug ? api.put('/landing-pages/' + slug, payload) : api.post('/landing-pages', payload);
export const getReferralCodes = () => api.get('/referrals');
export const createReferralCode = payload => api.post('/referrals/codes', payload);
export const getAnalyticsFunnel = () => api.get('/analytics/funnel');
export const getAnalyticsEvents = (limit = 20) => api.get('/analytics/events?limit=' + limit);
export const getServiceHealth = () => api.get('/service-health');
export const getPublicConfig = () => axios.get(PUBLIC_BASE + '/config');
export default api;
