require('dotenv').config();
const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const helmet = require('helmet');
const mongoose = require('mongoose');
const logger = require('./utils/logger');
const chatRoutes = require('./routes/chatRoutes');
const { setupSocketHandlers } = require('./socket/socketHandlers');
const { attachSocketRedisAdapter } = require('./services/socketRedisAdapter');
const { startChatArchiveJob } = require('./services/chatArchiveService');
const { errorHandler, notFoundHandler } = require('./middleware/errorHandler');
const { buildCorsOptions, socketCorsOptions } = require('./utils/corsOptions');
const { installExpressObservability } = require('../../shared/observability');
const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: socketCorsOptions() });
app.use(helmet()); app.use(require('cors')(buildCorsOptions())); app.use(express.json());
installExpressObservability(app, { serviceName: 'chat-service' });
mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/soulmatch_chat').then(() => logger.info('MongoDB connected')).catch(err => logger.error('MongoDB error:', err));
app.use('/api/v1/chat', chatRoutes);
app.get('/health', (req, res) => res.json({ status: 'ok', service: 'chat-service' }));
attachSocketRedisAdapter(io);
startChatArchiveJob();
setupSocketHandlers(io);
app.use(notFoundHandler);
app.use(errorHandler);
const PORT = process.env.PORT || 3005;
server.listen(PORT, () => logger.info('Chat Service on port ' + PORT));
module.exports = { app, server };
