require('dotenv').config();
const express = require('express');
const helmet = require('helmet');
const cors = require('cors');
const paymentRoutes = require('./routes/paymentRoutes');
const paymentController = require('./controllers/paymentController');
const { errorHandler, notFoundHandler } = require('./middleware/errorHandler');
const logger = require('./utils/logger');
const { buildCorsOptions } = require('./utils/corsOptions');
const { installExpressObservability } = require('../../shared/observability');
const { startSubscriptionExpiryJob } = require('./services/subscriptionExpiryService');
const app = express();
app.use(helmet()); app.use(cors(buildCorsOptions()));
installExpressObservability(app, { serviceName: 'payment-service' });
app.post('/api/v1/payment/webhook', express.raw({ type: 'application/json' }), paymentController.handleWebhook);
app.use(express.json());
app.use('/api/v1/payment', paymentRoutes);
app.get('/health', (req, res) => res.json({ status:'ok', service:'payment-service' }));
app.use(notFoundHandler);
app.use(errorHandler);
const PORT = process.env.PORT || 3007;
app.listen(PORT, () => logger.info('Payment Service on port ' + PORT));
startSubscriptionExpiryJob();
module.exports = app;
