const express = require('express');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const ctrl = require('../controllers/profileController');
const { authenticate } = require('../middleware/authMiddleware');
const router = express.Router();
const storage = multer.diskStorage({
  destination: (req, file, cb) => { const d = process.env.LOCAL_UPLOAD_DIR || './uploads'; fs.mkdirSync(d, { recursive: true }); cb(null, d); },
  filename: (req, file, cb) => cb(null, Date.now() + '-' + Math.random().toString(36).slice(2) + path.extname(file.originalname))
});
const photoUpload = multer({ storage, limits: { fileSize: 5*1024*1024 }, fileFilter: (req, file, cb) => { const ok = ['image/jpeg','image/png','image/webp'].includes(file.mimetype); cb(ok?null:new Error('JPG/PNG/WebP only'), ok); } });
const documentUpload = multer({ storage, limits: { fileSize: 10*1024*1024 }, fileFilter: (req, file, cb) => { const ok = ['image/jpeg','image/png','image/webp','application/pdf'].includes(file.mimetype); cb(ok?null:new Error('JPG/PNG/WebP/PDF only'), ok); } });
router.post('/create', authenticate, ctrl.createOrUpdateStep);
router.get('/me', authenticate, ctrl.getMyProfile);
router.get('/agent/me', authenticate, ctrl.getAgentProfile);
router.post('/agent/onboarding', authenticate, documentUpload.array('documents', 6), ctrl.upsertAgentOnboarding);
router.put('/agent/me', authenticate, ctrl.updateAgentProfile);
router.post('/agent/penny-drop/order', authenticate, ctrl.createAgentPennyDropOrder);
router.post('/agent/penny-drop/verify', authenticate, ctrl.verifyAgentPennyDropPayment);
router.get('/agent/membership', authenticate, ctrl.getAgentMembership);
router.get('/agent/membership/plans', authenticate, ctrl.getAgentMembershipPlans);
router.get('/agent/managed-profiles', authenticate, ctrl.listManagedProfiles);
router.post('/agent/managed-profiles', authenticate, ctrl.createManagedProfile);
router.get('/agent/managed-profiles/:profileId', authenticate, ctrl.getManagedProfile);
router.put('/agent/managed-profiles/:profileId', authenticate, ctrl.updateManagedProfile);
router.delete('/agent/managed-profiles/:profileId', authenticate, ctrl.deleteManagedProfile);
router.post('/agent/managed-profiles/:profileId/submit', authenticate, ctrl.submitManagedProfile);
router.get('/agent/managed-profiles/:profileId/documents', authenticate, ctrl.listManagedProfileDocuments);
router.post('/agent/managed-profiles/:profileId/documents', authenticate, documentUpload.array('documents', 4), ctrl.upsertManagedProfileDocument);
router.get('/assist/status', authenticate, ctrl.getAssistStatus);
router.put('/assist/status', authenticate, ctrl.updateAssistStatus);
router.patch('/status', authenticate, ctrl.updateProfileStatus);
router.get('/photo-access/requests', authenticate, ctrl.getPhotoAccessRequests);
router.put('/photo-access/requests/:requestId', authenticate, ctrl.respondPhotoAccessRequest);
router.get('/family-decisions', authenticate, ctrl.getFamilyDecisions);
router.post('/family-decisions/:familyDecisionId/comments', authenticate, ctrl.addFamilyDecisionComment);
router.put('/family-decisions/:targetProfileId', authenticate, ctrl.upsertFamilyDecision);
router.post('/:profileId/match-feedback', authenticate, ctrl.recordMatchFeedback);
router.get('/:profileId', authenticate, ctrl.getProfile);
router.post('/:profileId/contact/unmask', authenticate, ctrl.unlockContact);
router.post('/:profileId/ai/bio-suggestions', authenticate, ctrl.suggestProfileBio);
router.post('/:profileId/ai/icebreakers', authenticate, ctrl.generateIcebreakers);
router.put('/:profileId', authenticate, ctrl.updateProfile);
router.get('/:profileId/verifications', authenticate, ctrl.getVerifications);
router.post('/:profileId/verifications/upload', authenticate, documentUpload.single('document'), ctrl.submitVerificationUpload);
router.post('/:profileId/verifications', authenticate, ctrl.submitVerification);
router.get('/:profileId/photos', authenticate, ctrl.getPhotos);
router.post('/:profileId/photos', authenticate, photoUpload.array('photos', 10), ctrl.uploadPhotos);
router.delete('/:profileId/photos/:photoId', authenticate, ctrl.deletePhoto);
router.put('/:profileId/photos/:photoId/primary', authenticate, ctrl.setPrimaryPhoto);
router.post('/:profileId/photo-access/request', authenticate, ctrl.requestPhotoAccess);
router.get('/:profileId/preferences', authenticate, ctrl.getPreferences);
router.put('/:profileId/preferences', authenticate, ctrl.updatePreferences);
router.get('/:profileId/completion', authenticate, ctrl.getCompletion);
router.put('/:profileId/privacy', authenticate, ctrl.updatePrivacy);
router.post('/:profileId/view', authenticate, ctrl.recordView);
router.get('/:profileId/viewers', authenticate, ctrl.getViewers);
router.post('/:profileId/block', authenticate, ctrl.blockProfile);
router.post('/:profileId/report', authenticate, ctrl.reportProfile);
module.exports = router;
